name: Generate standalone Bun executable
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-push-release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run test
      - run: bun run build
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            substreams-sink-clickhouse
